### ISSUE TITLE
[debug build][Android] layout: Screen content is not scrollable when keyboards pops.

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#2981]
[**Note**: This issue has only been seen on debug builds of the app, which makes it a low priority. If you see it on a release build, please comment!]

---------------

Example: In realmScreen, on medium size phone. When url input is focused, input doesn't move to top making space for keyboard. So just after entering url, one need to press back button to hide keyboard and then then he can see `Enter` button.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/18511177/45838649-dfc2d380-bd2f-11e8-8a6f-d71b182e62c6.png">

@zulipbot claim

**Comment by jainkuniya** [comment]
I can only reproduce it on Emulator (Google pixel, API 26), but can't on my physical device (One plus 6, API 26).

Also on the emulator on current master I can reproduce 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/18511177/45839321-ad19da80-bd31-11e8-830a-c21aaa285564.png">

**Comment by borisyankov** [comment]
I'd suggest again to test on RN 0.57 :)

**Comment by jainkuniya** [comment]
>I'd suggest again to test on RN 0.57 :)

I tested on #2955, still can reproduce on Pixel 2 emulator and this time on my Android physical device too.

![](https://user-images.githubusercontent.com/18511177/45839321-ad19da80-bd31-11e8-830a-c21aaa285564.png)

**Comment by gnprice** [comment]
WFM in 25.4.118, on a Pixel 2 XL with Android 9. (With the display scaled way up in system settings, so that there's not a lot of room.)

@jainkuniya , would you try again to reproduce with a current version? Perhaps we've fixed it since the original report.

**Comment by jainkuniya** [comment]
Still can reproduce on 0b8920ae (upstream/master) on Android Pixel Genymotion emulator Android 9. 
![image](https://user-images.githubusercontent.com/18511177/59556578-353bc080-8fe2-11e9-8970-efdd39cf8060.png)

But can't on my physical One plus six Android 9.


This is not even reproducible even after clearing storage and restarting app.

And it is only reproducible on first launch of the app, from subsequent launches it works fine. 
![image](https://user-images.githubusercontent.com/18511177/59556504-2ef91480-8fe1-11e9-9947-cfc3dd9b09b4.png)


I think we should close this issue. In case if some user reports similar issue then we can resume on this.

**Comment by gnprice** [comment]
Thanks @jainkuniya !

I think actually your screenshot doesn't match the original report of this issue. If you look back at the top of this thread, you'll see you wrote there:

> When url input is focused, input doesn't move to top making space for keyboard. So just after entering url, one need to press back button to hide keyboard and then then he can see `Enter` button.

And the screenshot shows the app with the app bar still visible as normal, and the URL input field hasn't moved up appropriately.

Whereas in your screenshot above (of the bad case), the app bar *isn't* visible -- it's as if it's been pushed up above the screen. The compose box has also been pushed upward... though not quite as much as it should be.

Take a look at #3010. I think the issue you're seeing in that recent screenshot matches that issue exactly.

Looking closer at your later screenshots above, from after the original report: they also look like #3010 and your most recent screenshot.

---

So, those later reports look like a dupe of #3010.

I'm still interested in confirming that the original issue is gone, though -- the one in the original description and screenshot. Would you try reproducing it, on the same screen that that original description is about?

**Comment by jainkuniya** [comment]
I thought both are similar issue and was thinking that we are tracking both here. (as both are reproducible on emulator on first launch).

Yup! original issue is still reproducible on emulator, debug build on first launch. Can also reproduce it (along with #3010) on my physical device on first launch in debug mode.

**Comment by gnprice** [comment]
Hmm -- well, one key fact about #3010 is that it's only ever been seen in debug mode.

Can you reproduce this one in release mode?

**Comment by gnprice** [comment]
If this one turns out to be debug-mode-only, then we'll deprioritize it (just like #3010) and focus on other things.

If it turns out to affect release mode, then it's something that potentially affects many users' onboarding and first impressions, and we'll want to debug some more.

**Comment by jainkuniya** [comment]
> Can you reproduce this one in release mode?

Nope, I can only reproduce it in debug mode.

**Comment by jainkuniya** [comment]
Updated title and issue, to reflect it is only on debug build.

**Comment by gnprice** [comment]
Cool. Thanks for checking that! We'll leave this open but basically treat it as bottom-priority to debug any further, then.
