### ISSUE TITLE
iOS App uploads images as HEIC instead of JPG

### ISSUE THREAD

**Issue by rvjr** [zulip/zulip-mobile#5930]
Hi everyone,

I just noticed that my iOS Zulip app (30.0.266) uploads image from the photo library as Heic again. There is an old thread with a similar issue (https://github.com/zulip/zulip-mobile/issues/2178), but this is obviously occuring again, at least for me on Zulip Server 9.2. I also checked that the file itself is indeed not a jpeg, in terms of internal encoding, when I download it again on my pc.

For Heic the previews don't work, and it would make a lot of sense to convert them to jpg again on the mobile device.

Can anybody comment on this? Is there a workaround?

Best regards, Rainer

**Comment by FeldrinH** [comment]
The latest version of the iOS app is developed at https://github.com/zulip/zulip-flutter, so you probably want to submit your issue there

**Comment by gnprice** [comment]
Thanks @rvjr for the report, and thanks @FeldrinH for the reply 🙂 

That version number confirms that we're indeed talking about the new app. Either that repo, or in Zulip in [the #mobile channel on chat.zulip.org](https://chat.zulip.org/#narrow/channel/48-mobile), would be a good venue to discuss further.

I'd be particularly interested in hearing more about this part:
> For Heic the previews don't work

One thing that's changed since #2178 is that the server now converts HEIF/HEIC files to JPEG for use where needed. So it's expected that things should work just fine when the mobile app uploads an HEIC file; if it doesn't, we'd like to hear more so we can resolve that.

**Comment by gnprice** [comment]
(I wondered if the issue you were seeing might be https://github.com/zulip/zulip-flutter/issues/1785 . But it turns out 30.0.266 is the version where we fixed that issue, so at that version HEIC images should be displaying just fine.)

**Comment by rvjr** [comment]
Hm, I quickly checked this again, but it is reproducible on my mobile. If I upload via the image button, it is only displayed as link, in the app, the desktop app, and in the browser.

<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/2abc8c7b-db23-429e-9f1a-47d739ddf7d7" />

Interestingly I do see some heic images from other users, which others have posted in public channels, and these are diplayed as preview everywhere. Maybe I can find out how they were posted...

**Comment by chrisbobbe** [comment]
I suspect https://github.com/zulip/zulip/pull/34970 is the fix; you mentioned your Zulip Server version is 9.2. Please [upgrade your Zulip server to the latest version](https://zulip.readthedocs.io/en/11.1/production/upgrade.html#upgrading-to-a-release), or at least to [10.4](https://zulip.readthedocs.io/en/11.1/overview/changelog.html#zulip-server-10-4) in which that change was backported:

> Added backported `libheif` packages, required to thumbnail images taken on iOS 18.

**Comment by rvjr** [comment]
That sounds like a plan. Updating will take some time; if it doesn't solve it, I will post back here! Thank you very much!

**Comment by rvjr** [comment]
Just a quick feedback: we updated to 11.4 and it works now! Thank you all!

**Comment by chrisbobbe** [comment]
Yay, glad to hear it! :)
